name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Clang
      run: |
        cd build
        export CXX=clang++
        rm CMakeCache.txt -f
        cmake ..
        make
    - name: Build GCC
      run: |
        cd build
        export CXX=g++
        rm CMakeCache.txt -f
        cmake ..
        make
    - uses: actions/upload-artifact@master
      with:
        name: artifact
        path: build/
